services:
  nginx:
    image: nginx:stable-alpine
    container_name: mody_nginx
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - mody-network

  php:
    image: wordpress:6.7.1-php8.1-fpm-alpine
    container_name: mody_php
    volumes:
      - ./app:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: $DB_USER
      WORDPRESS_DB_PASSWORD: $DB_PASSWORD
      WORDPRESS_DB_NAME: $DB_NAME
    depends_on:
      - mariadb
    networks:
      - mody-network

  mariadb:
    image: mariadb:10.6
    container_name: mody_mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    networks:
      - mody-network

volumes:
  mariadb_data:

networks:
  mody-network:
    driver: bridge