#!/bin/bash

set -e

PROJECT_ROOT=$(pwd)

SOURCE_PATH="${PROJECT_ROOT}/app/wp"
TARGET_PATH="${PROJECT_ROOT}/app"

if [ -f "${TARGET_PATH}/wp-config.php" ]; then
    read -p "wp-config.php already exists. Do you want to replace it? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Operation cancelled. No changes were made."
        exit 0
    fi
    echo "Replacing existing wp-config.php..."
fi


echo "Generating wp-config.php from .env file..."

# Source the .env file to get variables
if [ -f "${PROJECT_ROOT}/.env" ]; then
    set -a
    source "${PROJECT_ROOT}/.env"
    set +a
else
    echo "Error: .env file not found in ${PROJECT_ROOT}. Please create one."
    exit 1
fi

# Get WordPress salts from the API and store in a variable
SALTS=$(curl -s https://api.wordpress.org/secret-key/1.1/salt/)

# Generate wp-config.php file content
cat > "${TARGET_PATH}/wp-config.php" <<EOF
<?php
/**
 * The base configuration for WordPress
 *
 * This file is generated by the generate-wp-config.sh script.
 * You can edit this file to customize your WordPress installation.
 */

// ** MySQL settings - You can get this info from your web host ** //
/** The name of the database for WordPress */
define('DB_NAME', '$DB_NAME');

/** MySQL database username */
define('DB_USER', '$DB_USER');

/** MySQL database password */
define('DB_PASSWORD', '$DB_PASSWORD');

/** MySQL hostname */
define('DB_HOST', '$DB_HOST');

/** Database Charset to use in creating database tables. */
define('DB_CHARSET', 'utf8mb4');

/** The Database Collate type. Don't change this if in doubt. */
define('DB_COLLATE', '');

${SALTS}

/**
 * WordPress database table prefix.
 *
 * You can have multiple installations in one database if you give each
 * a unique prefix. Only numbers, letters, and underscores please!
 */
\$table_prefix = 'wp_';

/**
 * For developers: WordPress debugging mode.
 *
 * Change this to true to enable the display of notices during development.
 * It is strongly recommended that plugin and theme developers use WP_DEBUG
 * in their development environments.
 */
define('WP_DEBUG', ${WP_DEBUG:-false});

/**
 * Enable Debug Logging to the /wp-content/debug.log file
 *
 * @link https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/
 */
define('WP_DEBUG_LOG', ${WP_DEBUG_LOG:-false});

/**
 * Disable display of errors and warnings
 */
define('WP_DEBUG_DISPLAY', ${WP_DEBUG_DISPLAY:-false});

/**
 * Define the WordPress environment type, e.g., 'development', 'staging', 'production'.
 */
define('WP_ENVIRONMENT_TYPE', '${WP_ENVIRONMENT_TYPE:-development}');

/**
 * Extra WordPress configuration from environment variables.
 */
${WORDPRESS_CONFIG_EXTRA:-}

/* That's all, stop editing! Happy publishing. */

/** Absolute path to the WordPress directory. */
if ( ! defined('ABSPATH') ) {
    define('ABSPATH', __DIR__ . '/');
}

/** Sets up WordPress vars and included files. */
require_once(ABSPATH . 'wp-settings.php');
EOF

echo "wp-config.php created successfully in the 'app' directory."